version: '3.9'

services:
  laravel-app:
    build:
      context: .
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql-db
    networks:
      - app-network
    command: >
      sh -c "
        composer install &&
        npm install --prefix /var/www/html &&
        npm run build --prefix /var/www/html &&
        php artisan key:generate &&
        php artisan migrate &&
        apache2-foreground
      "

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
